rust_arch:
  - x86_64-unknown-linux-gnu    # [linux64]
  - aarch64-unknown-linux-gnu   # [aarch64]
  - powerpc64le-unknown-linux-gnu       # [ppc64le]
  - x86_64-pc-windows-msvc      # [win64]
  - x86_64-apple-darwin         # [osx and x86_64]
  - aarch64-apple-darwin        # [osx and arm64]

# Use a higher deployment target on osx-64 due to
# https://github.com/conda-forge/rust-feedstock/issues/73
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.10                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.10                  # [osx and x86_64]
