{% set version = "1.29.2" %}

package:
  name: rust
  version: {{ version }}

source:
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz       # [osx]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz    # [win64]
  sha256: e9809825c546969a9609ff94b2793c9107d7d9bed67d557ed9969e673137e8d8  # [linux]
  sha256: 63f54e3013406b39fcb5b84bcf5e8ce85860d0b97a1e156700e467bf5fb5d5f2  # [osx]
  sha256: 7813396fb99021e9a8bccb2fc7e71b1b730d5f3aebbb09ffcc2ecb838a1073b4  # [win64]

build:
  number: 1001
  # the distributed binaries are already relocatable
  binary_relocation: False

requirements:
  build:
    - posix  # [win]
  run:
    - {{ compiler('c') }}  # [linux] -- rustc needs a toolchain to link executables on Linux

test:
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
