{% set version = "1.29.1" %}

package:
  name: rust
  version: {{ version }}

source:
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz       # [osx]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz    # [win64]
  sha256: b36998aea6d58525f25d89f1813b6bfd4cad6ff467e27bd11e761a20dde43745  # [linux]
  sha256: 07b07fbd6fab2390e19550beb8008745a8626cc5e97b72dc659061c1c3b3d008  # [osx]
  sha256: ec15b45be27b4406122518b2949f6186f0d9d422f23a946ab4de43716cc8e492  # [win64]

build:
  number: 0
  # the distributed binaries are already relocatable
  binary_relocation: False

requirements:
  build:
    - posix  # [win]

test:
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
