{% set version = "1.48.0" %}
{% set year = "2020" %}
{% set month = "09" %}
{% set day = "18" %}


package:
  name: rust
  version: {{ version }}.dev{{ year }}{{ month }}{{ day }}

source:
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win64]
  sha256: 72c7f3012f697a9fccc08a05eebadfaa0306ee011ed0818bfe3a29f7afa438e8  # [linux and x86_64]
  sha256: 567ce4035b45b3256a018140726b11ef44dc95a1fbee1aab3f5c3f2477317541  # [aarch64]
  sha256: 61d56d103327ebb975084d1014b06f0c5441d92ec2070a1c9096b1b6e8622d51  # [ppc64le]
  sha256: 0ff0ed7388fc99a483f86fa3218948fa060e1c2babfec3d0f4097ff37086f315  # [osx]
  sha256: ed7a48a463fda4408056d39a1118993060b6d60eb7b8c925b024ffba6aac8331  # [win64]

build:
  number: 0
  # the distributed binaries are already relocatable
  binary_relocation: false

requirements:
  build:
    - posix  # [win]
  run:
    - {{ compiler('c') }}  # [linux] -- rustc needs a toolchain to link executables on Linux

test:
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
    - andfoy
