{% set version = "1.34.1" %}

package:
  name: rust
  version: {{ version }}

source:
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz       # [osx]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz    # [win64]
  sha256: 8e2eead11bd5bf61409e29018d007c6fc874bcda2ff54db3d04d1691e779c14e  # [linux]
  sha256: f4e46b9994ccfab4a84059298d1dc8fd446b1bbb7449462e0459948f7debea0e  # [osx]
  sha256: 3b771a51f680bdf38e8e799fb3d9a76370be02e5968a55f7650a96bda7a4a0f5  # [win64]

build:
  number: 0
  # the distributed binaries are already relocatable
  binary_relocation: False

requirements:
  build:
    - posix  # [win]
  run:
    - {{ compiler('c') }}  # [linux] -- rustc needs a toolchain to link executables on Linux

test:
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
