{% set version = "1.51.0" %}

package:
  name: rust-split
  version: {{ version }}

source:
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz  # [osx and x86_64]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-apple-darwin.tar.gz  # [osx and arm64]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz  # [win64]
  sha256: 9e125977aa13f012a68fdc6663629c685745091ae244f0587dd55ea4e3a3e42f  # [linux and x86_64]
  sha256: fd31c78fffad52c03cac5a7c1ee5db3f34b2a77d7bc862707c0f71e209180a84  # [aarch64]
  sha256: 7362f561104d7be4836507d3a53cd39444efcdf065813d559beb1f54ce9f7680  # [ppc64le]
  sha256: 765212098a415996b767d1e372ce266caf94027402b269fec33291fffc085ca4  # [osx and x86_64]
  sha256: 95d0410bbd20b05f8b7d5adf70e8737873995bc86611a90e643d7081ca35147f  # [osx and arm64]
  sha256: aa0a7c78c68a2f23b72a95976f74aa5b883feb20812698b8ee0b07a86314ebc5  # [win64]
  patches:
    - 0001-gh-106-install.sh-Perfomance-Use-more-shell-builtins.diff

build:
  number: 0

requirements:
  build:
    - posix  # [win]
  host:

outputs:
  - name: rust-std-{{ rust_arch }}
    build:
      noarch: generic
      binary_relocation: false
      merge_build_host: false
    requirements:
      build:
        - posix  # [win]
      host:
      run:
    script: install-rust-std.sh  # [unix]
    script: install-rust-std.bat  # [win]
    test:
      commands:
        - test -d $PREFIX/lib/rustlib   # [unix]
        - if not exist %LIBRARY_PREFIX%/lib/rustlib exit 1  # [win]
        - echo {{ rust_arch }}

  - name: rust
    script: install-rust.sh  # [unix]
    script: install-rust.bat  # [win]
    build:
      # the distributed binaries are already relocatable
      binary_relocation: false
    run_exports:
      strong_constrains:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    requirements:
      build:
        - posix  # [win]
      host:
        - {{ pin_subpackage("rust-std-" ~ rust_arch, exact=True) }}
        - {{ compiler('c') }}  # [linux] -- rustc needs a toolchain to link executables
      run:
        - {{ pin_subpackage("rust-std-" ~ rust_arch, exact=True) }}
        - gcc_impl_{{ target_platform }}  # [linux]
    test:
      requires:
        - posix  # [win]
      commands:
        - set "REQUESTS_CA_BUNDLE="  # [win]
        - set "SSL_CERT_FILE="       # [win]
        - unset REQUESTS_CA_BUNDLE  # [unix]
        - unset SSL_CERT_FILE       # [unix]
        - rustc --help
        - rustdoc --help
        - cargo --help
        - cargo install --force xsv
        - echo {{ rust_arch }}

about:
  home: https://www.rust-lang.org
  license: MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
    - isuruf
