{% set version = "1.30.0" %}

package:
  name: rust
  version: {{ version }}

source:
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz       # [osx]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz    # [win64]
  sha256: f620e3125cc505c842150bd873c0603432b6cee984cdae8b226cf92c8aa1a80f  # [linux]
  sha256: 07008d90932712282bc599f1e9a226e97879c758dc1f935e6e2675e45694cc1b  # [osx]
  sha256: 960ca17c0c62ee250647c20b617e75912badb67ca8ade08c3224410a7c320ade  # [win64]

build:
  number: 1000
  # the distributed binaries are already relocatable
  binary_relocation: False

requirements:
  build:
    - posix  # [win]
  run:
    - {{ compiler('c') }}  # [linux] -- rustc needs a toolchain to link executables on Linux

test:
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
