travis:
  secure:
    BINSTAR_TOKEN: DHpcprgBMluqhhPl2mfjwkKdmIS9os0qVzd9e0Y3xTUA7fk/99qQa0zMrqdpiWyTFFuiIC+2wiLXoZzMS8UtqJA0+Kl7KGLkUs8vtsu7GTlFhANIgn6amBFugdr6D2upiklNOwAzMbmKBwbj6/J8vd7P04zRIXhQPeh1rJsq2qeds6QdVHsrMIIYlBijwl9rHrbdMBYyZfb9qlnszoDxIAgUUNYHu4UETuvZpj+GhfhhOEXW4O2sYArx0X6wbouSVs0LEKvEiPuCmL5XtocUsKd/c2h0/452P/mHCRLtfJh5+WcK13pWApuMOvGSCQwzU8ts0hyfypsw4xFCXlyN0ZEN9ZQ3SuMurBXohtt4C+ChD72/HCqyZ/Be49ssHdQunVZ1fslQX2vTp8xcWxWVnrl1ma5mm1v7gp0Y/AbFXLs/oBHTUX9wxc6/L/g5I5vcYkmiBvsLKfjo4ep/04kRyKto3k8oHI3ALFQwVAX3zOfepmHKF/5+5lU9JjFTcKYh/k/aDiQ+/wuEECBAgv5uSEMHAkXWxOdrIOr4Yo82u1qRCtnq1DpR+YmgTdJUd7yorqhKESScSOOrzYJdc2b5kQJ4WU0LSI5wmBe+UEbWgXN3GqRszBOVd5ZaeWGWa8h3O1dhU+WN4BrjGV9Hm/5ybCvpZ6yOsdieLEENbdfqu8s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
