provider:
  linux_ppc64le: default
build_platform:
  # Cross build linux-aarch64 due to CI timeout on native.
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
test_on_native_only: true
