travis:
  secure:
    BINSTAR_TOKEN: MsCZVq3UdMdvMenG8uMYbw+ga9WdCASWPSZZUU4KVVebR8M/xm8piRvhz5vOkMYlM10tEHgkqdiBTmaNGTOkA6YlWTC+eQhYQQfhqM5d0RYjzObhE3HVPsCeDBRbO6Tqw8eDsPOI/rtgm/4GWrwbnnvLmxCFpV5LIinoinGEh/GsUoMuexuW16il9RJjEtI1ooSCqRq+AjwxE5XN8Hs3ETvtSL5nbIq7GIX6CxW1aKnyagpJlMgb460S/nITUb9oTrX3hsHwGBAXIHw8CA6S01yhPJYEK/vgH+K93jI5bAQ3wlygc5Pz7+EzuKJWDA4hRS5XqUfZhYTBHFCGHs6b/JxkaO2CAdgwNVcVJGHZ0abQFLEkHvcOZIxBqHTIf8QmX0SUl27LCbodvHUvC6oke0ECPdmuYNJg64Q/DPGd6vfM9H/OF7H2rKBq8CWoOEjZFG3FyYBD6z16i5pqF1JE/77HMiFXEbijOTnT81KXYHz3Dgc7pNh9nevjfGywyg52OCGgOO2cAYHHktPxZGq4GhlztzzwR9QEG5da11XyJMRQlj3xFXqO/YJ1q9h/WQEjqV4e5KDJDYp2zJY1PcGHnqHy0yQ/J+Gq2j5v1yCFgDLC7XpHg4UW2Z4IT/L9u3tYh8l6gZ93COUnNVjEDiV+HH+zU/ISVn+E7kdcFQYpapM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
